public enum RingSegmentType
{
    Ring_1_Normal,
    Ring_1_Gap,
    Ring_1_Crumbling,
    Ring_1_Spike,
    Ring_2_Normal,
    Ring_2_Gap,
    Ring_2_Crumbling,
    Ring_2_Spike,
    Ring_3_Normal,
    Ring_3_Gap,
    Ring_3_Crumbling,
    Ring_3_Spike,
    Ring_4_Normal,
    Ring_4_Gap,
    Ring_4_Crumbling,
    Ring_4_Spike
}