public enum RingSegmentType
{
    Ring_0_Norm,
    Ring_0_Gap,
    Ring_0_Crumbling,
    Ring_0_Spike,
    Ring_1_Norm,
    Ring_1_Gap,
    Ring_1_Crumbling,
    Ring_1_Spike,
    Ring_2_Norm,
    Ring_2_Gap,
    Ring_2_Crumbling,
    Ring_2_Spike,
    Ring_3_Norm,
    Ring_3_Gap,
    Ring_3_Crumbling,
    Ring_3_Spike
}